### ISSUE TITLE
Can it built to mobile native app?

### ISSUE THREAD

**Issue by nvcken** [RustyVolley/RustyVolleySrc#8]

**Comment by codec-abc** [comment]
I don't know for sure. It depends if the framework I use (Quicksilver) can support it. From the Readme it doesn't look like it. @ryanisaacg can you confirm or infirm if Quicksilver support mobile devices?

But even if Quicksilver support it, the input would have to be adapted since I only handle keyboard. Also, I fear that mobile touch won't be precise enough to make the game enjoyable.

**Comment by ryanisaacg** [comment]
Quicksilver does not support mobile devices.

**Comment by codec-abc** [comment]
Thanks. So no support for mobile.
